<a href="https://colab.research.google.com/github/matvid/Proyecto-2/blob/main/Proyecto_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount ("/content/drive")

Mounted at /content/drive

In [ ]:
# Importar librerías generales
import numpy as np
import pandas as pd

# **Primera opción: conjunto de datos 1**

### *In Hospital Mortality Prediction*

In [ ]:
filename1 = ("/content/drive/MyDrive/Bootcamp/Coding Dojo/Proyecto 2/Data/opcion1.csv")
df1 = pd.read_csv(filename1)

In [ ]:
df1.head()

,group,ID,outcome,age,gendera,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
0,1,125047,0.0,72,1,37.588179,0,0,0,1,...,138.750000,7.463636,109.166667,13.166667,2.618182,7.230,21.166667,0.5,40.0,55
1,1,139812,0.0,75,2,NaN,0,0,0,0,...,138.888889,8.162500,98.444444,11.444444,1.887500,7.225,33.444444,0.5,78.0,55
2,1,109787,0.0,83,2,26.572634,0,0,0,0,...,140.714286,8.266667,105.857143,10.000000,2.157143,7.268,30.571429,0.5,71.5,35
3,1,130587,0.0,43,2,83.264629,0,0,0,0,...,138.500000,9.476923,92.071429,12.357143,1.942857,7.370,38.571429,0.6,75.0,55
4,1,138290,0.0,75,2,31.824842,1,0,0,0,...,136.666667,8.733333,104.500000,15.166667,1.650000,7.250,22.000000,0.6,50.0,55

In [ ]:
df1.tail()

,group,ID,outcome,age,gendera,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
1172,2,171130,0.0,62,1,25.516870,1,1,0,1,...,136.714286,10.271429,94.428571,20.142857,2.714286,NaN,27.714286,NaN,NaN,40
1173,2,101659,0.0,78,1,25.822710,0,1,0,1,...,135.680000,10.523529,101.720000,18.160000,2.012500,NaN,20.480000,NaN,NaN,30
1174,2,162069,0.0,85,2,23.891779,1,1,0,1,...,136.000000,8.466667,97.285714,14.000000,2.028571,NaN,28.857143,NaN,NaN,55
1175,2,120967,0.0,79,2,35.288554,0,0,1,1,...,140.000000,8.183333,104.000000,15.750000,2.090000,NaN,24.375000,NaN,NaN,25
1176,2,107636,0.0,47,1,23.121384,1,0,0,1,...,135.285714,9.085714,93.857143,20.285714,2.566667,NaN,26.571429,NaN,NaN,55

In [ ]:
df1.shape
print(f"El dataframe consta de", df1.shape[0], "filas y", df1.shape[1], "columnas.")

El dataframe consta de 1177 filas y 51 columnas.

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1177 entries, 0 to 1176
Data columns (total 51 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   group                     1177 non-null   int64
 1   ID                        1177 non-null   int64
 2   outcome                   1176 non-null   float64
 3   age                       1177 non-null   int64
 4   gendera                   1177 non-null   int64
 5   BMI                       962 non-null    float64
 6   hypertensive              1177 non-null   int64
 7   atrialfibrillation        1177 non-null   int64
 8   CHD with no MI            1177 non-null   int64
 9   diabetes                  1177 non-null   int64
 10  deficiencyanemias         1177 non-null   int64
 11  depression                1177 non-null   int64
 12  Hyperlipemia              1177 non-null   int64
 13  Renal failure             1177 non-null   int64
 14  COPD                      1177 non-null   int64
 15  heart rate                1164 non-null   float64
 16  Systolic blood pressure   1161 non-null   float64
 17  Diastolic blood pressure  1161 non-null   float64
 18  Respiratory rate          1164 non-null   float64
 19  temperature               1158 non-null   float64
 20  SP O2                     1164 non-null   float64
 21  Urine output              1141 non-null   float64
 22  hematocrit                1177 non-null   float64
 23  RBC                       1177 non-null   float64
 24  MCH                       1177 non-null   float64
 25  MCHC                      1177 non-null   float64
 26  MCV                       1177 non-null   float64
 27  RDW                       1177 non-null   float64
 28  Leucocyte                 1177 non-null   float64
 29  Platelets                 1177 non-null   float64
 30  Neutrophils               1033 non-null   float64
 31  Basophils                 918 non-null    float64
 32  Lymphocyte                1032 non-null   float64
 33  PT                        1157 non-null   float64
 34  INR                       1157 non-null   float64
 35  NT-proBNP                 1177 non-null   float64
 36  Creatine kinase           1012 non-null   float64
 37  Creatinine                1177 non-null   float64
 38  Urea nitrogen             1177 non-null   float64
 39  glucose                   1159 non-null   float64
 40  Blood potassium           1177 non-null   float64
 41  Blood sodium              1177 non-null   float64
 42  Blood calcium             1176 non-null   float64
 43  Chloride                  1177 non-null   float64
 44  Anion gap                 1177 non-null   float64
 45  Magnesium ion             1177 non-null   float64
 46  PH                        885 non-null    float64
 47  Bicarbonate               1177 non-null   float64
 48  Lactic acid               948 non-null    float64
 49  PCO2                      883 non-null    float64
 50  EF                        1177 non-null   int64
dtypes: float64(37), int64(14)
memory usage: 469.1 KB

### **1) Fuente de datos**

Kaggle: https://www.kaggle.com/datasets/saurabhshahane/in-hospital-mortality-prediction

El conjunto de datos proviene de la base de datos MIMIC-III, que es una base de datos de pacientes hospitalizados en el Hospital Beth Israel Deaconess Medical Center de Boston, Massachusetts.

### **2) Breve descripción de datos**

El conjunto de datos contiene información sobre pacientes hospitalizados, incluidos sus datos demográficos, médicos y de laboratorio.

Por lo anterior, es necesario revisar predictores de mortalidad hospitalaria de pacientes con insuficiencia cardíaca ingresados ​​en UCI.

### **3) ¿Cuál es el objetivo?**

El objetivo es predecir si un paciente morirá en el Hospital Beth Israel Deaconess Medical Center de Boston, Massachusetts.

### **4) ¿Este es un problema de clasificación o regresión?**

Este es un problema de clasificación binaria, ya que el objetivo es predecir si un paciente morirá o no.

### **5) ¿Cuántas características hay?**

El conjunto de datos contiene 51 características.

### **6) ¿Cuántas filas de datos hay?**

El conjunto de datos contiene 1.177 filas de datos.

### **7) ¿Qué retos, si es que hay alguno, prevén en la limpieza, exploración o modelización con este conjunto de datos?**

Algunos retos que se pueden prever en la limpieza, exploración o modelización con este conjunto de datos son:

- Ausencias de datos: El conjunto de datos contiene algunas ausencias de datos, lo que puede dificultar la limpieza y el análisis.
- Datos sesgados: El conjunto de datos puede estar sesgado, ya que se basa en datos de pacientes hospitalizados en un único hospital.
- Dificultad de interpretación: Algunas de las características del conjunto de datos pueden ser difíciles de interpretar, lo que puede dificultar la selección de características y el modelado.

En general, este es un conjunto de datos complejo que presenta algunos retos. Sin embargo, también es un conjunto de datos valioso que puede utilizarse para mejorar la predicción de la mortalidad hospitalaria.

# **Segunda opción: conjunto de datos 2**

In [ ]:
filename2 = ("/content/drive/MyDrive/Bootcamp/Coding Dojo/Proyecto 2/Data/opcion2.csv")
df2 = pd.read_csv(filename2)

In [ ]:
df2.head()

,Country,Region,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,...,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
0,Turkiye,Middle East,2015,11.1,13.0,105.8240,1.32,97,65,27.8,...,97,0.08,11006,78.53,4.9,4.8,7.8,0,1,76.5
1,Spain,European Union,2015,2.7,3.3,57.9025,10.35,97,94,26.0,...,97,0.09,25742,46.44,0.6,0.5,9.7,1,0,82.8
2,India,Asia,2007,51.5,67.9,201.0765,1.57,60,35,21.2,...,64,0.13,1076,1183.21,27.1,28.0,5.0,0,1,65.4
3,Guyana,South America,2006,32.8,40.5,222.1965,5.68,93,74,25.3,...,93,0.79,4146,0.75,5.7,5.5,7.9,0,1,67.0
4,Israel,Middle East,2012,3.4,4.3,57.9510,2.89,97,89,27.0,...,94,0.08,33995,7.91,1.2,1.1,12.8,1,0,81.7

In [ ]:
df2.tail()

,Country,Region,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,...,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
2859,Niger,Africa,2000,97.0,224.9,291.8240,0.092,72,64,20.8,...,34,0.49,399,11.33,12.8,12.9,1.1,0,1,49.9
2860,Mongolia,Asia,2009,23.9,28.6,235.2330,6.560,97,97,25.3,...,95,0.02,2515,2.67,2.2,2.3,9.1,0,1,66.9
2861,Sri Lanka,Asia,2004,17.7,28.9,134.8950,1.560,62,95,21.9,...,97,0.02,2130,19.39,15.4,15.5,10.3,0,1,74.3
2862,Lithuania,European Union,2002,7.9,9.9,204.0120,11.000,94,95,26.1,...,95,0.05,7424,3.44,3.3,3.3,11.1,1,0,71.8
2863,Iceland,Rest of Europe,2011,2.1,2.6,50.5745,6.840,88,90,26.1,...,95,0.05,48934,0.32,0.9,0.9,11.0,1,0,82.4

In [ ]:
df2.shape
print(f"El dataframe consta de", df2.shape[0], "filas y", df2.shape[1], "columnas.")

El dataframe consta de 2864 filas y 21 columnas.

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2864 entries, 0 to 2863
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      2864 non-null   object
 1   Region                       2864 non-null   object
 2   Year                         2864 non-null   int64
 3   Infant_deaths                2864 non-null   float64
 4   Under_five_deaths            2864 non-null   float64
 5   Adult_mortality              2864 non-null   float64
 6   Alcohol_consumption          2864 non-null   float64
 7   Hepatitis_B                  2864 non-null   int64
 8   Measles                      2864 non-null   int64
 9   BMI                          2864 non-null   float64
 10  Polio                        2864 non-null   int64
 11  Diphtheria                   2864 non-null   int64
 12  Incidents_HIV                2864 non-null   float64
 13  GDP_per_capita               2864 non-null   int64
 14  Population_mln               2864 non-null   float64
 15  Thinness_ten_nineteen_years  2864 non-null   float64
 16  Thinness_five_nine_years     2864 non-null   float64
 17  Schooling                    2864 non-null   float64
 18  Economy_status_Developed     2864 non-null   int64
 19  Economy_status_Developing    2864 non-null   int64
 20  Life_expectancy              2864 non-null   float64
dtypes: float64(11), int64(8), object(2)
memory usage: 470.0+ KB

### **1) Fuente de datos**

Kaggle: https://www.kaggle.com/datasets/lashagoch/life-expectancy-who-updated

El conjunto de datos proviene de la Organización Mundial de la Salud (OMS).

### **2) Breve descripción de datos**

El conjunto de datos contiene información sobre la esperanza de vida al nacer para hombres y mujeres en 2022. Los datos se presentan por país, región y grupo de edad. Esto puede proporcionar una panorámica detallada de múltiples indicadores claves, permitiendo así, identificar tendencias de salud.

### **3) ¿Cuál es el objetivo?**

El objetivo es predecir información sobre la esperanza de vida al nacer en todo el mundo.

### **4) ¿Este es un problema de clasificación o regresión?**

Este es un problema de regresión, ya que el objetivo es predecir un valor numérico, la esperanza de vida.

### **5) ¿Cuántas características hay?**

El conjunto de datos contiene 21 características.

### **6) ¿Cuántas filas de datos hay?**

El conjunto de datos contiene 2.864 filas de datos.

### **7) ¿Qué retos, si es que hay alguno, prevén en la limpieza, exploración o modelización con este conjunto de datos?**

Algunos retos que se pueden prever en la limpieza, exploración o modelización con este conjunto de datos son:

- Dificultad de interpretación: Algunas de las características del conjunto de datos pueden ser difíciles de interpretar, lo que puede dificultar la selección de características y el modelado.